const sun = {
    number: "00",
    tagline: "Our Star",
    name: "The Sun",
    description:
        "The Sun is a yellow dwarf star, a hot ball of glowing gases at the heart of our solar system. Its gravity holds the solar system together, keeping everything – from the biggest planets to the smallest particles of debris – in its orbit. The connection and interactions between the Sun and Earth drive the seasons, ocean currents, weather, climate, radiation belts and auroras.",
    img: "sun.jpg",
    type: "Yellow Dwarf",
    planets: "8",
    radius: "695,508",
    distance: "26,000 light years",
    age: "~ 4.5 billion years",
};

const planets = [
    {
        number: "01",
        tagline: "The Swiftest Planet",
        name: "Mercury",
        description:
            "The smallest planet in our solar system and nearest to the Sun, Mercury is only slightly larger than Earth’s Moon. From the surface of Mercury, the Sun would appear more than three times as large as it does when viewed from Earth, and the sunlight would be as much as seven times brighter. Mercury is appropriately named for the swiftest of the ancient Roman gods.",
        img: "mercury.jpg",
        type: "Terrestrial",
        moons: "0",
        radius: "2,439.7",
        distance: "57,909,227",
        day_length: "176 earth days",
        year_length: "88",
    },
    {
        number: "02",
        tagline: "Planetary Hot Spot",
        name: "Venus",
        description:
            "Similar in structure and size to Earth, Venus spins slowly in the opposite direction from most planets. Its thick atmosphere traps heat in a runaway greenhouse effect, making it the hottest planet in our solar system with surface temperatures hot enough to melt lead. Glimpses below the clouds reveal volcanoes and deformed mountains.",
        img: "venus.jpg",
        type: "Terrestrial",
        moons: "0",
        radius: "6,051.8",
        distance: "108,209,475",
        day_length: "243 earth days",
        year_length: "225",
    },
    {
        number: "03",
        tagline: "Our Home Planet",
        name: "Earth",
        description:
            "Our home planet is the third planet from the Sun, and the only place we know of so far that’s inhabited by living things. While Earth is only the fifth largest planet in the solar system, it is the only world in our solar system with liquid water on the surface. Just slightly larger than nearby Venus, Earth is the biggest of the four planets closest to the Sun, all of which are made of rock and metal.",
        img: "earth.jpg",
        type: "Terrestrial",
        moons: "1",
        radius: "6,371.00",
        distance: "149,598,262",
        day_length: "1 earth days",
        year_length: "365",
    },
    {
        number: "04",
        tagline: "The Red Planet",
        name: "Mars",
        description:
            "The fourth planet from the Sun, Mars is a dusty, cold, desert world with a very thin atmosphere. This dynamic planet has seasons, polar ice caps and weather and canyons and extinct volcanoes, evidence it was once an even more active past. Mars is one of the most explored bodies in our solar system, and it’s the only planet where we’ve sent rovers to roam the alien landscape.",
        img: "mars.jpg",
        type: "Terrestrial",
        moons: "2",
        radius: "3,389.5",
        distance: "227,943,824",
        day_length: "24.6 hours",
        year_length: "687",
    },
    {
        number: "05",
        tagline: "The Grandest Planet",
        name: "Jupiter",
        description:
            "Jupiter is the fifth planet from our Sun and is, by far, the largest planet in the solar system – more than twice as massive as all the other planets combined. Jupiter’s stripes and swirls are actually cold, windy clouds of ammonia and water, floating in an atmosphere of hydrogen and helium. Jupiter’s iconic Great Red Spot is a giant storm bigger than Earth that has raged for hundreds of years.",
        img: "jupiter.jpg",
        type: "Gas Giant",
        moons: "53",
        radius: "69,911",
        distance: "778,340,821",
        day_length: "9.93 hours",
        year_length: "4,333",
    },
    {
        number: "06",
        tagline: "Jewel of Our Solar System",
        name: "Saturn",
        description:
            "Saturn is the sixth planet from the Sun and the second largest planet in our solar system. Adorned with a dazzling system of icy rings, Saturn is unique among the planets. It is not the only planet to have rings, but none are as spectacular or as complex as Saturn’s. Like fellow gas giant Jupiter, Saturn is a massive ball made mostly of hydrogen and helium.",
        img: "saturn.jpg",
        type: "Gas Giant",
        moons: "53",
        radius: "58,232",
        distance: "1,426,666,422",
        day_length: "10.7 hours",
        year_length: "10,759",
    },
    {
        number: "07",
        tagline: "The Sideways Planet",
        name: "Uranus",
        description:
            "The seventh planet from the Sun with the third largest diameter in our solar system, Uranus is very cold and windy. The ice giant is surrounded by 13 faint rings and 27 small moons as it rotates at a nearly 90-degree angle from the plane of its orbit. This unique tilt makes Uranus appear to spin on its side, orbiting the Sun like a rolling ball.",
        img: "uranus.jpg",
        type: "Ice Giant",
        moons: "27",
        radius: "25,362",
        distance: "2,870,658,186",
        day_length: "17 hours",
        year_length: "30,687",
    },
    {
        number: "08",
        tagline: "The Windiest Planet",
        name: "Neptune",
        description:
            "Dark, cold and whipped by supersonic winds, ice giant Neptune is the eighth and most distant planet in our solar system. More than 30 times as far from the Sun as Earth, Neptune is the only planet in our solar system not visible to the naked eye. In 2011 Neptune completed its first 165-year orbit since its discovery in 1846.",
        img: "neptune.jpg",
        type: "Ice Giant",
        moons: "14",
        radius: "24,622",
        distance: "4,498,396,441",
        day_length: "16 hours",
        year_length: "60,190",
    },
];
